# Generated by Django 5.0.14 on 2025-12-28
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_hardwarescan_bundle_hash_hardwarescan_client_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="computer_serial",
            field=models.CharField(
                max_length=200,
                blank=True,
                null=True,
                db_index=True,
                help_text='Computer serial (from lshw "Device Serial Number", normalized at query time)',
            ),
        ),
    ]
